[project]
name = "brennan-complexity"
version = "0.1.0"
description = "Explore thoughts about complexity and entropy"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ipython>=9.1.0",
    "numpy>=2.2.4",
    "pre-commit>=4.2.0",
    "ruff>=0.11.6",
]

